server:
  port: 8081
logging:
  level:
    com.github.tobato.fastdfs.domain.conn.ConnectionManager: debug

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 172.16.1.51:22122
    - 172.16.1.50:22122
  pool:
    #从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: 700
    #获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 5000
    #每个key最大连接数
    max-total-per-key: 50
    #每个key对应的连接池最大空闲连接数
    max-idle-per-key: 10
    #每个key对应的连接池最小空闲连接数
    min-idle-per-key: 5
  retry-after-second: 180
#=================================================================================
# 自定义参数相关配置

#=================================================================================
fdfs-ip-value:
  #    172.16.1.155:22122  #测试
#  172.16.1.180:22122 #测试
#    56.35.130.15:22122  #东区公安-正式#
#  56.37.177.55:22122  #西区公安-正式